services:
  - type: web
    name: nexus-chat-backend
    env: node
    plan: free
    buildCommand: cd frontend && npm ci && npm run build && cd ../backend && npm ci
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://nexuschat-l9mc.onrender.com/api
      - key: MONGO_URI
        value: mongodb+srv://nexuschat_user:NexusChat2026@cluster0.lbqllmy.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: f836322454cdf66e7a4e8e94df9e89ce8d37d5023558b4bef61cfecb1268817b
      - key: CLOUDINARY_CLOUD_NAME
        value: daighlwid
      - key: CLOUDINARY_API_KEY
        value: 853914822757919
      - key: CLOUDINARY_API_SECRET
        value: ldQZgsOv9-hEyt6B7BC3HT8iqWg
